name: XcodeGenSample

options:
  bundleIdPrefix: com.shunya.yamada

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    majorVersion: 6.0.0

targets:
  App:
    type: application
    platform: iOS
    scheme: {}
    sources: App
    dependencies:
      - package: Kingfisher
      - target: Core

  Core:
    type: framework
    platform: iOS
    sources: Core
